#!/bin/bash

#---------Xmonad files-------------
x_f1=~/.xmonad/xmonad.hs
x_f2=~/.bashrc
x_f3=~/.config/xmobar/xmobarrc
x_f4=~/.config/nvim/init.vim

#--------- I3 files----------
i3_f1=~/.config/i3/config
i3_f2=~/.bashrc
i3_f3=~/.config/alacritty/alacritty.yml
i3_f4=~/.config/nvim/init.vim
i3_f5=~/.config/i3/i3blocks/i3blocks.conf
i3_f6=~/.config/i3/my_i3lock.sh
i3_f7=~/.config/multilock/config
i3_f8=~/.config/picom/picom.conf

#3>&1 1>&2 2>&3 3>&-

#---------Variables--------------
wm=$(ps -e | grep -m 1 -oF	\
		-e xmonad	\
		-e i3		)


#----------Dialog box for Xmonad--------------

xmonad(){

    File=$(dialog \
        --title "CONFIGS" --menu "Select file" "Location" 0 0 0 \
        1 "Xmonad" "$i3_f1" 2 "Bash" 3 "Xmobar" 4 "Nvim"  \
       --stdout)
    
    clear
    
    case $File in 
        '1')
    	nvim $x_f1
    	;;
        '2')
    	nvim $x_f2
    	;;
        '3')
    	nvim $x_f3
    	;;
        '4')
    	nvim $x_f4
    	;;
        *)
    	echo "No files selected"
    	;;
    esac

}

#---------Dialog box for I3----------------

i3(){
    File=$(zenity --list \
	--width=600 --height=450 \
        --title "Configs" \
	--column="ID" --column="Select file" --column="Select file" \
        1 "I3" "$i3_f1" 2 "Bashrc" "$i3_f2" 3 "Alacritty" "$i3_f3" 4 "Nvim" "$i3_f4" \
	5 "I3 blocks" "$i3_f5" 6 "I3 Lock" "$i3_f6" 7 "Multilock" "$i3_f7" 8 "Picom" "$i3_f8") 

    case $File in 
        '1')
    	nvim $i3_f1
    	;;
        '2')
    	nvim $i3_f2
    	;;
        '3')
    	nvim $i3_f3
    	;;
        '4')
    	nvim $i3_f4
    	;;
        '5')
    	nvim $i3_f5
    	;;
        '6')
    	nvim $i3_f6
    	;;
        '7')
    	nvim $i3_f7
    	;;
        '8')
    	nvim $i3_f8
    	;;
        *)
    	echo "No files selected"
    	;;
    esac
}

if [[ $wm == "i3" ]]; then
    i3
elif [[ $wm == "xmonad" ]]; then
    xmonad
else
    echo "Unidentified Window Manager"
fi
