#!/bin/bash

#This is a visual cd.

while :
do
    echo "$PWD"
    mapfile -t -O 1 my_array < <(ls --color=auto)
    my_array[0]='..' 
    num=0

    for list in "${my_array[@]}"
    do
	echo -e " |\e[38;5;202m$num\e[0m ⟶ $list"
	((num++))
    done
    
    read -p "Type your number: " -t 30 -r value

    case $value in
	'0')
	    cd ..
	    echo -e " Location \e[92mchanged\e[0m"
	    echo  "----------------------------------------"
	;;

	[1-9]|[1-9][0-9]|100) 
	    cd ${my_array[$value]} 
	    echo -e "Location \e[92mchanged\e[0m"
	    echo  "----------------------------------------"
	;;

	'q') cd $PWD
	    break 
	;;
	*) break ;;
    esac

    unset my_array
done

