#!/bin/bash


FILE_NAME="$1"
#touch $1
FILE_TYPE=$(echo $FILE_NAME | cut -d'.' -f 2)
echo "File Extension: $FILE_TYPE"

open_file () {
    touch $FILE_NAME
    echo "File created"
    sleep 1s
    $EDITOR $FILE_NAME
}

case $FILE_TYPE in 
    py | c | cpp | js | html | sh | txt | css | h | hpp)
	open_file;;
    *) echo "file doesnt exsist";;
esac
