#!/bin/bash
#Simple script for making a files
#STudent_DIRectories

start_dir=$(PWD)

if [[ -e $1 ]]; then
   rm -rf $1 
   mkdir $1
   cd $1
else 
    mkdir $1
    cd $1
fi


if [[ $start_dir != $PWD ]]; then
    mkdir "Labs"
    mkdir "Assignments"
    mkdir "Notes"
fi
#mkdir Labs && mkdir Exams && mkdir Notes

echo "Folders Created"
