#!/bin/bash

echo -e "\n$(date "+%d-%m-%Y --- %T") --- Starting work\n"

sudo apt update
sudo apt -y full-upgrade

sudo apt -y autoremove
sudo apt autoclean

echo -e "\n$(date "+%T") ---  Script Terminated"
