#!/bin/bash

echo -e "\n$(date "+%d-%m-%Y --- %T") --- Starting work\n"

sudo apt update
sudo apt full-upgrade

sudo apt autoremove
sudo apt autoclean

echo -e "\n$(date "+%T") ---  Script Terminated"
