#!/bin/bash

echo -e "\n$(date "+%d-%m-%Y --- %T") --- Starting work\n"

sudo apt update
sudo apt upgrade -y

sudo apt autoremove -y
sudo apt autoclean

echo -e "\n$(date "+%T") ---  Script Terminated"
